name: Python Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13.7'
      - name: Install dependencies
        run: |
          pip install -r GithubActions/1.Ariketa/src/requirements.txt
      - name: Run tests
        run: pytest GithubActions/1.Ariketa/src/test.py
      - name: ruff tests
        run: ruff check .
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ghcr.io/${{ JosuDelaFlor/Agile }}/python-test:latest
        name: TestBuildImage
        run: |
          docker run ghcr.io/${{ github.repository_owner }}/python-test:latest